### ISSUE TITLE
Unused parameter build error

### ISSUE THREAD

**Issue by skottmckay** [dcleblanc/SafeInt#13]
Unused parameter 't' in NegationHelper<T, false>::Negative causes build error on MacOS.

/Users/runner/runners/2.164.8/work/1/s/cmake/external/SafeInt/safeint/SafeInt.hpp:1054:41: error: unused parameter 't' [-Werror,-Wunused-parameter]
    _CONSTEXPR14 static bool Negative(T t, T& /*out*/)

```
template < typename T > class NegationHelper <T, false> // unsigned
{
public:
    template <typename E>
    _CONSTEXPR14 static T NegativeThrow( T t ) SAFEINT_CPP_THROW
    {
#if defined SAFEINT_DISALLOW_UNSIGNED_NEGATION
        static_assert( sizeof(T) == 0, "Unsigned negation is unsupported" );
#endif
        // This may not be the most efficient approach, but you shouldn't be doing this
        return (T)SignedNegation<std::int64_t>::Value(t);
    }

    _CONSTEXPR14 static bool Negative(T t, T& /*out*/)
    {
        // This will only be used by the SafeNegation function
        return false;
    }
};
```

**Comment by dcleblanc** [comment]
Should be fixed, let me know if you encounter any more issues. I'm not going to make a change this small into a full release. I do have the ability to test on gcc and clang on Linux, and VS on Windows, but not MacOS. While I'd like one day to convert the project to CMake, right now, I just have make files. If you'd like to clone one of the two test folders, and make a MacOS version, I'd be happy to check that in.
