### ISSUE TITLE
Support for building with exceptions disabled

### ISSUE THREAD

**Issue by skottmckay** [dcleblanc/SafeInt#15]
Is it possible to use SafeInt in a build with exceptions disabled? 

Currently the below 'throw SafeIntException(...)' statements seem to be problematic in that sort of build. Perhaps there's a way to work around that I'm missing. If not, could `SafeIntExceptionHandler<SafeIntException>` be #ifdef'd out if SafeIntDefaultExceptionHandler is not using that class? 

https://github.com/dcleblanc/SafeInt/blob/34a1b2191deb89eca9db4e5e1cfe5e72e70eb472/SafeInt.hpp#L698-L713

**Comment by dcleblanc** [comment]
Yes, you can define whatever exception handler you like. Several teams in Office have use __failfast as the handler – no catchable exceptions, just kill the app. Also, you only hit that block if you’ve defined VISUAL_STUDIO_SAFEINT_COMPAT, which is really old, and I’m considering dropping support for it. If you do have code that was originally using the Visual Studio version, which is about a decade old, and hasn’t been updated in forever, I’d advise switching to this version, and fix up whatever needs fixing, which it probably minimal.

What you typically want to do is to define this – SafeIntDefaultExceptionHandler, and then implement whatever it is that you’d like to happen, or if running on Windows, just use the failfast option.

Also, if you’re in a situation where you don’t want exceptions, there is a set of non-throwing functions that return a bool.

**Comment by skottmckay** [comment]
We have a custom handler which uses a throw macro that handles exceptions being available/unavailable. We don't set VISUAL_STUDIO_SAFEINT_COMPAT. I don't believe it will hit that block of code with the raw 'throw' statements but the compiler still sees that code, so if you have exceptions disabled that generates an error. 

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/common/safeint.h

We build cross platform so a Windows specific fail fast path isn't an option. We also generally build with exceptions enabled and changing all the SafeInt usage to the non-throwing variants would be a massive code change vs. having a way just to exclude the default SafeIntExceptionHandler implementation from the build, or replace the 'throw' used there via some macro. 

If you only expect that default handler to be used if VISUAL_STUDIO_SAFEINT_COMPAT is defined could it be #ifdef'd out if that is not the case?

**Comment by dcleblanc** [comment]
So there’s probably a bug on your side or mine – anything that’s inside an #ifdef that’s false should never been seen by the compiler. I’m not expecting that code to be compiled.

If you need to do several different things, then I would define my own exception handler in a file which then includes SafeInt, and then ifdef to get what I want on each platform or build version.

You can test this pretty easily with

#if defined FOO
#error foo defined
#endif

So if you want to diagnose which code blocks are seen by the compiler, that’s how to run it down. If there’s a bug in my code, I’ll push a fix right away.

**Comment by skottmckay** [comment]
What are you expecting should be able to #ifdef out the `template <> class SafeIntExceptionHandler < SafeIntException >` implementation in the header? 

It's not currently inside a check on whether VISUAL_STUDIO_SAFEINT_COMPAT is defined, and I don't see any other #define's could exclude that section of the header.

**Comment by dcleblanc** [comment]
OK, sorry, I thought the whole block was within a #define – there’s a good bit of stuff that’s actually not needed if you bring your own exception handler.

What you should do as a work-around is #define out this:

    template <> class SafeIntExceptionHandler < SafeIntException >
    {
    public:

        static SAFEINT_NORETURN void SAFEINT_STDCALL SafeIntOnOverflow()
        {
            SafeIntExceptionAssert();
            throw SafeIntException(SafeIntError::SafeIntArithmeticOverflow );
        }

        static SAFEINT_NORETURN void SAFEINT_STDCALL SafeIntOnDivZero()
        {
            SafeIntExceptionAssert();
            throw SafeIntException(SafeIntError::SafeIntDivideByZero );
        }
    };

And the corresponding typedef below. And then define your own exception handler that does what you want. I’ll fiddle with this a bit once I get a chance, but it may be a few days.

**Comment by skottmckay** [comment]
Any ETA on this change being made? Thanks!

**Comment by dcleblanc** [comment]
I will do this tomorrow

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dcleblanc** [comment]
Hi, Scott - a draft for this is in a branch - https://github.com/dcleblanc/SafeInt/tree/fix/no_except

Please take a look, and give it a try. I am in the process of setting up a Linux system that I can use to test this with clang and gcc, can't check it into main until I have some actual compile runs. This _should_ work, done testing with latest Visual Studio.

**Comment by gwang-msft** [comment]
We are triggering multiple CIs in this PR, https://github.com/microsoft/onnxruntime/pull/5216, to test compiling on multiple platforms.

**Comment by dcleblanc** [comment]
This is now closed as fixed, merged into main. Thanks for reporting this issue.

**Comment by skottmckay** [comment]
Thank you! Much appreciated.
