### ISSUE TITLE
Add constexpr support

### ISSUE THREAD

**Issue by DanielJump** [dcleblanc/SafeInt#2]
Most SafeInt expressions can be constexpr.

**Comment by dcleblanc** [comment]
OK, I agree, but do you see examples of places that could benefit? Go ahead and fix this if you like, or explain a bit more where you'd like to see changes.

**Comment by dcleblanc** [comment]
constexpr support is going to be a problem because Visual Studio doesn't correctly set __cplusplus value.

**Comment by dcleblanc** [comment]
Done, lot of work
