### ISSUE TITLE
Use int128 with clang/gcc.

### ISSUE THREAD

**Issue by jaykrell** [dcleblanc/SafeInt#21]
Something very much like this, but adapt to safeint names/conventions (safe/bool).

``` 
 typedef unsigned __int128 uint128_t; 
 typedef __int128 int128_t; 
  
 _Must_inspect_result_ 
DKSTATUS 
 Multiply64Unsigned( 
     uint64_t in1, 
     uint64_t in2, 
     _Out_ _Deref_out_range_(==, in1 * in2) uint64_t* out) 
 { 
     const uint128_t result = static_cast<uint128_t>(in1) * static_cast<uint128_t>(in2); 
     const uint64_t resultHigh = static_cast<uint64_t>(result >> 64); 
     uint64_t resultLow = static_cast<uint64_t>(result); 
     DKSTATUS status = STATUS_SUCCESS; 
  
     if (resultHigh != 0) 
     { 
         resultLow = ~static_cast<uint64_t>(0); // Error like ntintsafe.h. 
         status = STATUS_INTEGER_OVERFLOW; 
     } 
  
     *out = resultLow; 
   
     return status; 
} 
 
 _Must_inspect_result_ 
 DKSTATUS 
 Multiply64( 
     int64_t in1, 
     int64_t in2, 
     _Out_ _Deref_out_range_(==, in1 * in2) int64_t* out) 
 { 
     const int128_t result = static_cast<int128_t>(in1) * static_cast<int128_t>(in2); 
     const int64_t resultHigh = static_cast<int64_t>(result >> 64); 
     int64_t resultLow = static_cast<int64_t>(result); 
     DKSTATUS status = STATUS_SUCCESS; 
  
     // The upper 65 bits must have the same value, else overflow. 
     // 
     if ((resultLow < 0 && resultHigh != -1) || (resultLow >= 0 && resultHigh != 0)) 
     { 
         resultLow = -1; // Error like ntintsafe.h. 
         status = STATUS_INTEGER_OVERFLOW; 
     }
 
     *out = resultLow;
 
    return status;
}
```

**Comment by dcleblanc** [comment]
Clang and gcc have an intrinsic that I can use, and I’ve been meaning to go incorporate that. Last time I checked, few compilers supported 128-bit ints, so what I think I’d rather do is just branch the intrinsics depending on which compiler set I have. Though I am curious to see when this was incorporated – if it has been available for a while, it may be worthwhile to leverage these.

What I don’t think I’m up for is expanding full support for 128-bit integers – we currently have 64 cases of size and signed or unsigned, and some operations have a lot of cases now. Having 100 combinations would be a lot of work.

**Comment by jaykrell** [comment]
I think int128 is well supported, but I admit I don't have details.
 I only actually target amd64 and arm64.

Stackoverlow suggests ifdef _SIZEOF_INT128_ or such.

I think int128 will compete well with overflow intrinsics,
and go back to further compilers. At least on 64bit targets.

You know, on AMD64 at least, in assembly, when you multiply
64x64, you always do get 128 bits out. So it is basically free.

When you do zero/sign-extended 64 => 128 => 128x128=128,
gcc/clang notice and just do 64x64=128.

I don't know what you mean by the 100 extra combinations.
 Well, maybe I do, below.

It works, that simply, any 64x64=64 + overflow
case, signed x signed, and unsigned x unsigned, can
be implemented by zero or sign extending to 128 bts
and then doing 128x128=128.

I think the answer is: I am not advocating exposing anything related to int128. Not safe or unsafe.
Just using int128 to implement safe 64bit multiplication.

The most important thing here though is willingness to collaborate.
The technical details are easier. :)
Granted, platform coverage can be a pain.
Autoconf is kinda pain, and so is the alternative, but I guess intrinsics can be queried.

**Comment by dcleblanc** [comment]
So the __int128 appears to be available on gcc/clang for the last 3 years, and is still not supported on Visual Studio, despite it working in Intellisense. I understand the advantages of casting upwards, that’s how I implemented multiplication checking for 32-bit – just cast to 64, and do appropriate checks for the upper 32 bits. I can also go use the gcc/clang intrinsics, which would get me more support in terms of versions, and I have an outstanding issue on that which I have been procrastinating on for some time. So, I think I’d prefer to do that, though I could do both, have to think about it. I will have some time in the next couple of weeks. As it stands, 64-bit checked multiplication consumes a half dozen instructions, and has some branches to be able to do it in standard code – that’s a bit bloated.

What I mean by having 100 cases is that we currently have 8, 16, 32 and 64-bit ints, signed and unsigned. The total number of combinations of those is 64. If we add 128-bit as a supported type, now we have 10 total signed/size combinations, so in any given operation, we could have now 100 x op y combinations. The 64 cases boil down to 23 equivalence cases, as seen in the IntRegion class. So you then have to go sort all that out, and worse yet, go add a bunch of new test cases to the test harness. That’s a LOT of work, and until int128 is a standard type, I don’t think I want to.

However, if they’re available, I can use them just to simplify 64-bit multiplication, which is my biggest pain point.

In terms of collaboration, don’t worry – I’ve supported this library for the last 17 years, and have no plans to change that.

**Comment by dcleblanc** [comment]
This should now be fixed in fix/intrinsic branch, that will be merged into main.

**Comment by jaykrell** [comment]
It looks about right, but for the right shift of a signed type. I would avoid that.

**Comment by dcleblanc** [comment]
I don't think it is undefined now that two's complement is standard, but it could sign fill, and that's a concern. I need to come up with another approach, then. I don't think I can make 128-bit literals though. Take a shot at it tomorrow, thanks for the review.

**Comment by dcleblanc** [comment]
Fixed
