### ISSUE TITLE
Allow SafeInt to support enums

### ISSUE THREAD

**Issue by DanielJump** [dcleblanc/SafeInt#3]
I believe the only change required is fixing IntTraits to include a cast.

        isSigned  = ( (T)(-1) < (T)0 ),

**Comment by dcleblanc** [comment]
Please see the section with this:

#if defined _LIBCPP_TYPE_TRAITS || defined _TYPE_TRAITS_

I thought that would allow this to work

**Comment by dcleblanc** [comment]
OK, made a test case, saw the repro, this is now fixed.
