### ISSUE TITLE
Instrument return values with [[nodiscard]] when compiler supports it? 

### ISSUE THREAD

**Issue by bgianfo** [dcleblanc/SafeInt#33]
It would be nice if the functions which return values like `SafeAdd(..)` were marked as [`[[nodiscard]]`](https://en.cppreference.com/w/cpp/language/attributes/nodiscard) to catch bugs where the caller doesn't properly observe the return value of the operation. 

You can feature detect `[[nodiscard]]` support by using the `__has_cpp_attribute(nodiscard)` macro.

**Comment by dcleblanc** [comment]
Sure, that’s a good suggestion, I’ll look into adding that to the next version.

**Comment by dcleblanc** [comment]
I know this has been a while, but it is finally being worked on in a branch.

**Comment by dcleblanc** [comment]
This got merged in today, and currently I'm only supporting [[nodiscard]], not the older declspec or attribute (depending on compiler). Sorting out which of those support what is a bit of a pain. I did find how to detect if MSVC has the older annotation, and could support that if needed. Please let me know if what I have is sufficient, or if you want down level compiler support.

**Comment by bgianfo** [comment]
What you have looks great, we don't need down level support.

Thanks!
